import time

from app.services.assessment.base import AssessmentResult, AssessmentRunner


class MockAssessmentRunner(AssessmentRunner):
    """Fast mock — returns pre-built annotation without network calls or PDF generation."""

    def run(
        self,
        job_id: str,
        variants: list[dict],
        workflow_config: dict | None = None,
    ) -> AssessmentResult:
        time.sleep(2)

        # Annotate the real incoming variants if provided, otherwise use built-in demo set
        source = variants if variants else _DEMO_VARIANTS

        annotated = []
        for i, v in enumerate(source[:20]):   # cap at 20 for mock speed
            base = dict(v)
            demo = _DEMO_VARIANTS[i % len(_DEMO_VARIANTS)]
            base.setdefault("gene",         demo["gene"])
            base.setdefault("significance", demo["significance"])
            base.setdefault("hotspot",      demo["hotspot"])
            base.setdefault("af",           demo.get("af"))
            base.setdefault("rsid",         demo.get("rsid", "."))
            annotated.append(base)

        pathogenic = sum(1 for a in annotated if "pathogenic" in a.get("significance", "").lower())
        hotspots   = sum(1 for a in annotated if a.get("hotspot"))

        return AssessmentResult(
            summary=(
                f"{len(annotated)} variants assessed (mock). "
                f"{pathogenic} pathogenic/likely pathogenic. "
                f"{hotspots} cancer hotspot(s) identified."
            ),
            variants=annotated,
            report_path=None,  # PDF only generated by RealAssessmentRunner
        )


_DEMO_VARIANTS = [
    {
        "chrom": "chr17", "pos": 7674220,  "ref": "G", "alt": "A",
        "gene": "TP53",   "significance": "Pathogenic",
        "hotspot": True,  "af": 0.0001,   "rsid": "rs28934578",
    },
    {
        "chrom": "chr13", "pos": 32340300, "ref": "A", "alt": "T",
        "gene": "BRCA2",  "significance": "Likely benign",
        "hotspot": False, "af": 0.014,    "rsid": "rs11571833",
    },
    {
        "chrom": "chr7",  "pos": 55191822, "ref": "T", "alt": "G",
        "gene": "EGFR",   "significance": "Pathogenic",
        "hotspot": True,  "af": 0.0003,   "rsid": "rs121434568",
    },
    {
        "chrom": "chr12", "pos": 25398284, "ref": "C", "alt": "T",
        "gene": "KRAS",   "significance": "Pathogenic",
        "hotspot": True,  "af": 0.0005,   "rsid": "rs121913529",
    },
    {
        "chrom": "chr9",  "pos": 107543332, "ref": "C", "alt": "T",
        "gene": "TSC1",   "significance": "Likely pathogenic",
        "hotspot": False, "af": 0.0002,   "rsid": "rs587776767",
    },
]
